version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: netflix-postgres
    environment:
      POSTGRES_DB: netflix_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  jupyter:
    build: .
    container_name: netflix-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    depends_on:
      - postgres
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

  streamlit:
    build: .
    container_name: netflix-streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
    command: streamlit run streamlit_dashboard.py --server.address 0.0.0.0

volumes:
  postgres_data: 